const vehicles = [
  {
  id: "2015-nissan-qashqai-st",
  title: "2015 Nissan QASHQAI ST J11 Auto",
  price: 12999,
  kms: "151,335 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12–36 month extended warranty options available",
  body: "SUV",
  colour: "Ivory Pearl",
  engine: "2.0L 4 Cylinder Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOQASHQAI",
  imageLabel: "Nissan QASHQAI",
  image: "assets/vehicles/Nissan Qashqai 2015/car_01.png",
  images: [
    "assets/vehicles/Nissan Qashqai 2015/car_02.png",
    "assets/vehicles/Nissan Qashqai 2015/car_01.png",
    "assets/vehicles/Nissan Qashqai 2015/car_03.png",
    "assets/vehicles/Nissan Qashqai 2015/car_04.png",
    "assets/vehicles/Nissan Qashqai 2015/car_05.png",
    "assets/vehicles/Nissan Qashqai 2015/car_06.png",
    "assets/vehicles/Nissan Qashqai 2015/car_07.png",
    "assets/vehicles/Nissan Qashqai 2015/car_08.png",
    "assets/vehicles/Nissan Qashqai 2015/car_09.png",
    "assets/vehicles/Nissan Qashqai 2015/car_10.png",
    "assets/vehicles/Nissan Qashqai 2015/car_11.png",
    "assets/vehicles/Nissan Qashqai 2015/car_12.png",
    "assets/vehicles/Nissan Qashqai 2015/car_13.png",
    "assets/vehicles/Nissan Qashqai 2015/car_14.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/nissan-qashqai-2015/oag-ad-25806740/",
  description: "2015 Nissan QASHQAI ST J11 Auto finished in Ivory Pearl with black interior. A reliable, economical and practical 5-seat SUV, ideal for daily driving, first car buyers or small families. Powered by a 2.0L 4-cylinder petrol engine with automatic CVT transmission and front-wheel drive, offering smooth driving and excellent fuel economy of 6.9L/100km combined. This QASHQAI has travelled 151,335km and is listed as drive away with roadworthy certificate included, registration until January 2027 and 12–36 month extended warranty options available.",
  features: [
    "Reverse camera",
    "Bluetooth",
    "Cruise control",
    "Air conditioning",
    "Power windows",
    "Multi-function steering wheel",
    "USB/AUX input",
    "4 speaker stereo",
    "17-inch alloy wheels",
    "LED daytime running lights",
    "Remote central locking",
    "Electric mirrors",
    "Split fold rear seats",
    "Spacious 430L boot",
    "Excellent fuel economy",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Hill holder",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2015-bmw-x5-xdrive30d-black",
  title: "2015 BMW X5 xDrive30d F15 Auto 4x4",
  price: 22000,
  kms: "156,605 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Azurite Black",
  engine: "3.0L 6 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGBMWF15X57SEAT",
  imageLabel: "BMW X5",
  image: "assets/vehicles/BMW X5 2015 Black/car_01.png",
  images: [
    "assets/vehicles/BMW X5 2015 Black/car_01.png",
    "assets/vehicles/BMW X5 2015 Black/car_02.png",
    "assets/vehicles/BMW X5 2015 Black/car_03.png",
    "assets/vehicles/BMW X5 2015 Black/car_04.png",
    "assets/vehicles/BMW X5 2015 Black/car_05.png",
    "assets/vehicles/BMW X5 2015 Black/car_06.png",
    "assets/vehicles/BMW X5 2015 Black/car_07.png",
    "assets/vehicles/BMW X5 2015 Black/car_08.png",
    "assets/vehicles/BMW X5 2015 Black/car_09.png",
    "assets/vehicles/BMW X5 2015 Black/car_10.png",
    "assets/vehicles/BMW X5 2015 Black/car_11.png",
    "assets/vehicles/BMW X5 2015 Black/car_12.png",
    "assets/vehicles/BMW X5 2015 Black/car_13.png",
    "assets/vehicles/BMW X5 2015 Black/car_14.png",
    "assets/vehicles/BMW X5 2015 Black/car_15.png",
    "assets/vehicles/BMW X5 2015 Black/car_16.png",
    "assets/vehicles/BMW X5 2015 Black/car_17.png",
    "assets/vehicles/BMW X5 2015 Black/car_18.png",
    "assets/vehicles/BMW X5 2015 Black/car_19.png",
    "assets/vehicles/BMW X5 2015 Black/car_20.png",
    "assets/vehicles/BMW X5 2015 Black/car_21.png",
    "assets/vehicles/BMW X5 2015 Black/car_22.png",
    "assets/vehicles/BMW X5 2015 Black/car_23.png",
    "assets/vehicles/BMW X5 2015 Black/car_24.png",
    "assets/vehicles/BMW X5 2015 Black/car_25.png",
    "assets/vehicles/BMW X5 2015 Black/car_26.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-x5-2015/oag-ad-25819559/",
  description: "2015 BMW X5 xDrive30d F15 Auto 4x4 finished in Azurite Black with black interior. A highly optioned luxury SUV offering powerful turbo diesel performance, premium comfort and strong practicality. Powered by a 3.0L 6-cylinder turbo diesel engine paired with an 8-speed sports automatic transmission and BMW xDrive all-wheel drive. This X5 has travelled 156,605km and is listed with roadworthy certificate provided, finance available and 12 month warranty included.",
  features: [
    "7 seat configuration",
    "Full leather interior",
    "Electric memory seats",
    "Panoramic sunroof",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "360 degree camera",
    "Adaptive cruise control",
    "Lane departure warning",
    "Blind spot monitoring",
    "Forward collision warning",
    "AEB low speed",
    "Dual-zone climate control",
    "Power tailgate",
    "Keyless entry",
    "Push-button start",
    "Premium sound system",
    "9 speaker stereo",
    "DVD player",
    "USB input",
    "AUX input",
    "iPod input",
    "Head-up display",
    "Voice recognition",
    "Automatic bi-xenon headlights",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Heated mirrors",
    "19-inch alloy wheels",
    "Roof rails",
    "Selectable driving modes",
    "Stop-start system",
    "Sports steering wheel",
    "Hill descent control",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Tyre pressure monitoring",
    "6 airbags"
  ]
},
{
  id: "2016-bmw-2-series-228i-sport-line",
  title: "2016 BMW 2 Series 228i Sport Line F22 Auto",
  price: 21990,
  kms: "94,880 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month warranty included",
  body: "Coupe",
  colour: "White",
  engine: "2.0L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOBMW2",
  imageLabel: "BMW 2 Series",
  image: "assets/vehicles/BMW 2 Series 2016/car_01.png",
  images: [
    "assets/vehicles/BMW 2 Series 2016/car_02.png",
    "assets/vehicles/BMW 2 Series 2016/car_01.png",
    "assets/vehicles/BMW 2 Series 2016/car_03.png",
    "assets/vehicles/BMW 2 Series 2016/car_04.png",
    "assets/vehicles/BMW 2 Series 2016/car_05.png",
    "assets/vehicles/BMW 2 Series 2016/car_06.png",
    "assets/vehicles/BMW 2 Series 2016/car_07.png",
    "assets/vehicles/BMW 2 Series 2016/car_08.png",
    "assets/vehicles/BMW 2 Series 2016/car_09.png",
    "assets/vehicles/BMW 2 Series 2016/car_10.png",
    "assets/vehicles/BMW 2 Series 2016/car_11.png",
    "assets/vehicles/BMW 2 Series 2016/car_12.png",
    "assets/vehicles/BMW 2 Series 2016/car_13.png",
    "assets/vehicles/BMW 2 Series 2016/car_14.png",
    "assets/vehicles/BMW 2 Series 2016/car_15.png",
    "assets/vehicles/BMW 2 Series 2016/car_16.png",
    "assets/vehicles/BMW 2 Series 2016/car_17.png",
    "assets/vehicles/BMW 2 Series 2016/car_18.png",
    "assets/vehicles/BMW 2 Series 2016/car_19.png",
    "assets/vehicles/BMW 2 Series 2016/car_20.png",
    "assets/vehicles/BMW 2 Series 2016/car_21.png",
    "assets/vehicles/BMW 2 Series 2016/car_22.png",
    "assets/vehicles/BMW 2 Series 2016/car_23.png",
    "assets/vehicles/BMW 2 Series 2016/car_24.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-2-series-2016/oag-ad-25897808/",
  description: "2016 BMW 2 Series 228i Sport Line F22 Auto finished in white with a stylish coupe body. A sporty and refined 2-door BMW coupe offering strong turbo petrol performance, premium comfort and everyday usability. Powered by a 2.0L turbo intercooled 4-cylinder petrol engine paired with an 8-speed sports automatic transmission and rear-wheel drive. This BMW 228i has travelled 94,880km and is listed with 12 month warranty included.",
  features: [
    "Bluetooth",
    "Reverse camera",
    "GPS satellite navigation",
    "Front parking sensors",
    "Rear parking sensors",
    "Cruise control",
    "Automatic headlights",
    "Bi-xenon headlights",
    "LED daytime running lights",
    "Front fog lamps",
    "Rear fog lamps",
    "Dual-zone climate control",
    "Leather interior",
    "Sports front seats",
    "Push-button start",
    "Digital radio",
    "USB input",
    "AUX input",
    "iPod input",
    "MP3 decoder",
    "Inbuilt harddisk drive",
    "6 speaker stereo",
    "Multi-function control screen",
    "Smart device app display/control",
    "Paddle shifters",
    "Selectable driving modes",
    "Sports steering wheel",
    "Electric power steering",
    "Rain-sensing wipers",
    "Heated washer jets",
    "Electric heated mirrors",
    "Trip computer",
    "On-board computer",
    "Tyre pressure monitoring",
    "18-inch alloy wheels",
    "Runflat tyres",
    "Rear wheel drive",
    "Stop-start system",
    "ABS brakes",
    "Brake assist",
    "Traction control",
    "Electronic stability control",
    "Corner braking control",
    "6 airbags"
  ]
},
{
  id: "2011-volkswagen-polo-gti",
  title: "2011 Volkswagen Polo GTI 6R Auto MY11",
  price: 11999,
  kms: "136,200 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month warranty included",
  body: "Hatchback",
  colour: "Deep Black",
  engine: "1.4L 4 Cylinder Turbo Supercharged Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGVWPOLOBK",
  imageLabel: "Volkswagen Polo",
  image: "assets/vehicles/Volkswagen Polo 2011/car_01.png",
  images: [
    "assets/vehicles/Volkswagen Polo 2011/car_01.png",
    "assets/vehicles/Volkswagen Polo 2011/car_02.png",
    "assets/vehicles/Volkswagen Polo 2011/car_03.png",
    "assets/vehicles/Volkswagen Polo 2011/car_04.png",
    "assets/vehicles/Volkswagen Polo 2011/car_05.png",
    "assets/vehicles/Volkswagen Polo 2011/car_06.png",
    "assets/vehicles/Volkswagen Polo 2011/car_07.png",
    "assets/vehicles/Volkswagen Polo 2011/car_08.png",
    "assets/vehicles/Volkswagen Polo 2011/car_09.png",
    "assets/vehicles/Volkswagen Polo 2011/car_10.png",
    "assets/vehicles/Volkswagen Polo 2011/car_11.png",
    "assets/vehicles/Volkswagen Polo 2011/car_12.png",
    "assets/vehicles/Volkswagen Polo 2011/car_13.png",
    "assets/vehicles/Volkswagen Polo 2011/car_14.png",
    "assets/vehicles/Volkswagen Polo 2011/car_15.png",
    "assets/vehicles/Volkswagen Polo 2011/car_16.png",
    "assets/vehicles/Volkswagen Polo 2011/car_17.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/volkswagen-polo-2011/oag-ad-25758432/",
  description: "2011 Volkswagen Polo GTI 6R Auto MY11 finished in Deep Black with black interior. A fun, sporty and practical compact hot hatch offering strong GTI performance, easy daily driving and great fuel economy. Powered by a 1.4L turbocharged and supercharged 4-cylinder petrol engine paired with a 7-speed DSG automatic transmission and front-wheel drive.",
  features: [
    "GTI performance hatch",
    "1.4L turbo supercharged engine",
    "7 speed DSG automatic",
    "Sport seats",
    "Bluetooth",
    "Cruise control",
    "Central locking",
    "Power windows",
    "Alloy wheels",
    "17-inch alloy wheels",
    "Front fog lamps",
    "Rear fog lamps",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Leather steering wheel",
    "Leather gear knob",
    "Split fold rear seats",
    "Sports suspension",
    "Sports pedals",
    "Electric heated mirrors",
    "6 speaker stereo",
    "AUX input",
    "MP3 decoder",
    "CD player",
    "Rear wiper",
    "Glovebox cooling",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Hill holder",
    "Electronic brake force distribution",
    "Tyre pressure monitoring",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2012-volkswagen-tiguan-132tsi-pacific",
  title: "2012 Volkswagen Tiguan 132TSI Pacific 5N Auto 4MOTION MY12.5",
  price: 7888,
  kms: "202,000 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Candy White",
  engine: "2.0L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGTIGUANTSI",
  imageLabel: "Volkswagen Tiguan",
  image: "assets/vehicles/Volkswagen Tiguan 2012/car_01.png",
  images: [
    "assets/vehicles/Volkswagen Tiguan 2012/car_01.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_02.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_03.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_04.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_05.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_06.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/volkswagen-tiguan-2012/oag-ad-26014328/",
  description: "2012 Volkswagen Tiguan 132TSI Pacific 5N Auto 4MOTION MY12.5 finished in Candy White with grey interior. A practical and comfortable compact SUV with all-wheel drive capability, useful family space and strong Volkswagen safety features. Powered by a 2.0L turbo intercooled 4-cylinder petrol engine paired with a 6-speed automatic transmission and 4MOTION all-wheel drive. Features include Bluetooth, front and rear parking sensors, cruise control, automatic headlights, dual-zone climate control, rear air conditioning, 8-speaker stereo, AUX/USB input, power windows, rain-sensing wipers, electric heated mirrors, roof rails, multi-function steering wheel, electric park brake, hill holder, traction control and electronic stability control. This Tiguan has travelled 202,000km and is listed as drive away, with 12 month warranty included.",
  features: [
    "Bluetooth",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Cruise control",
    "Automatic headlights",
    "Dual-zone climate control",
    "Rear air conditioning",
    "8 speaker stereo",
    "AUX input",
    "USB input",
    "MP3 decoder",
    "CD player",
    "Power windows",
    "Rain-sensing wipers",
    "Rear wiper",
    "Electric heated mirrors",
    "Remote central locking",
    "Engine immobiliser",
    "Multi-function steering wheel",
    "Trip computer",
    "Cloth interior",
    "Split fold rear seats",
    "Rear sliding seat adjustment",
    "Roof rails",
    "16-inch alloy wheels",
    "Electric park brake",
    "Hill holder",
    "Electronic differential lock",
    "4MOTION all-wheel drive",
    "Traction control",
    "Electronic stability control",
    "Rollover stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2017-mercedes-benz-gla220d",
  title: "2017 Mercedes-Benz GLA-Class GLA220 d Auto",
  price: 18888,
  kms: "125,349 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Cirrus White",
  engine: "2.1L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "ADFGADSF",
  imageLabel: "Mercedes-Benz GLA",
  image: "assets/vehicles/Mercedes Benz GLA 2017/car_01.png",
  images: [
    "assets/vehicles/Mercedes Benz GLA 2017/car_01.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_02.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_03.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_04.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/mercedes-benz-gla-class-2017/oag-ad-26016339/",
  description: "2017 Mercedes-Benz GLA220 d X156 Auto finished in Cirrus White with black interior. A premium compact luxury SUV offering strong turbo diesel efficiency, smooth automatic driving and a refined Mercedes-Benz cabin. Powered by a 2.1L turbo diesel 4-cylinder engine paired with a 7-speed sports automatic dual clutch transmission. Features include Apple CarPlay, Android Auto, satellite navigation, reverse camera, front and rear parking sensors, blind spot monitoring, autonomous emergency braking, dual-zone climate control, leather-look interior, heated front seats, electric front seats, keyless start, power tailgate, automatic bi-xenon headlights, rain-sensing wipers, Bluetooth, digital radio, 18-inch alloy wheels and excellent fuel economy. This GLA220 d has travelled 125,349km and is listed with roadworthy certificate, registration, finance available and 12 month premium warranty included.",
  features: [
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Automated parking assistance",
    "Blind spot monitoring",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Driver attention detection",
    "Cruise control",
    "Speed limiter",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Leather-look interior",
    "Heated front seats",
    "Electric front seats",
    "Electric lumbar support",
    "Keyless start",
    "Push-button start",
    "Power tailgate",
    "Digital radio",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "CD player",
    "Automatic bi-xenon headlights",
    "LED daytime running lights",
    "Rear fog lamps",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Tyre pressure monitoring",
    "Roof rails",
    "18-inch alloy wheels",
    "Runflat tyres",
    "Electric park brake",
    "Hill holder",
    "Stop-start system",
    "Selectable driving modes",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "9 airbags"
  ]
},
{
  id: "2015-mazda-cx5-grand-touring",
  title: "2015 Mazda CX-5 Grand Touring KE Series 2 Auto AWD",
  price: 12222,
  kms: "162,350 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Meteor Grey",
  engine: "2.2L 4 Cylinder Twin Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGMAZDACX5GT",
  imageLabel: "Mazda CX-5",
  image: "assets/vehicles/Mazda CX5 2015/car_01.png",
  images: [
    "assets/vehicles/Mazda CX5 2015/car_01.png",
    "assets/vehicles/Mazda CX5 2015/car_02.png",
    "assets/vehicles/Mazda CX5 2015/car_03.png",
    "assets/vehicles/Mazda CX5 2015/car_04.png",
    "assets/vehicles/Mazda CX5 2015/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/mazda-cx-5-2015/oag-ad-25758937/",
  description: "2015 Mazda CX-5 Grand Touring KE Series 2 Auto AWD finished in Meteor Grey with beige interior. A top-spec family SUV offering excellent diesel economy, premium comfort and strong practicality. Powered by a 2.2L twin turbo diesel 4-cylinder engine paired with a 6-speed SKYACTIV-Drive sports automatic transmission and all-wheel drive. Features include sunroof, full leather interior, heated front seats, satellite navigation, reverse camera, front and rear parking sensors, Bluetooth connectivity, cruise control, keyless entry, push-button start, dual-zone climate control, premium 9-speaker stereo, LED headlights, rain-sensing wipers, 19-inch alloy wheels and 5 star ANCAP safety rating. This CX-5 has travelled 162,350km and is listed with roadworthy certificate provided and 12 month warranty included.",
  features: [
    "Sunroof",
    "Full leather interior",
    "Heated front seats",
    "Electric front seats",
    "Driver memory seat",
    "Electric lumbar support",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Cruise control",
    "Keyless entry",
    "Push-button start",
    "Dual-zone climate control",
    "9 speaker premium stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "CD player",
    "Voice recognition",
    "Multi-function control screen",
    "Automatic LED headlights",
    "LED daytime running lights",
    "LED fog lights",
    "LED tail lights",
    "Rain-sensing wipers",
    "Electric anti-glare mirror",
    "Electric mirrors",
    "Multi-function steering wheel",
    "Trip computer",
    "Tyre pressure monitoring",
    "Split fold rear seats",
    "Cargo cover",
    "19-inch alloy wheels",
    "AWD",
    "2.2L twin turbo diesel",
    "Excellent fuel economy",
    "Stop-start system",
    "Electric park brake",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2014-range-rover-evoque-td4-pure-tech",
  title: "2014 Land Rover Range Rover Evoque TD4 Pure Tech Auto 4x4 MY15",
  price: 17777,
  kms: "154,239 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Fuji White",
  engine: "2.2L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGLANDDISC5",
  imageLabel: "Range Rover Evoque",
  image: "assets/vehicles/Range Rover Evoque 2014/car_01.png",
  images: [
    "assets/vehicles/Range Rover Evoque 2014/car_01.png",
    "assets/vehicles/Range Rover Evoque 2014/car_02.png",
    "assets/vehicles/Range Rover Evoque 2014/car_03.png",
    "assets/vehicles/Range Rover Evoque 2014/car_04.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/land-rover-range-rover-evoque-2014/oag-ad-25830599/",
  description: "2014 Land Rover Range Rover Evoque TD4 Pure Tech Auto 4x4 MY15 finished in Fuji White with black interior. A stylish compact luxury SUV offering strong diesel performance, premium comfort and confident 4x4 capability. Powered by a 2.2L turbo diesel 4-cylinder engine paired with a 9-speed sports automatic transmission and constant 4x4 drive. Features include leather interior, satellite navigation, reverse camera, front and rear parking sensors, keyless entry, push-button start, dual-zone climate control, Bluetooth connectivity, Meridian sound system, cruise control, multi-function steering wheel, 18-inch alloy wheels, daytime running lights and all-terrain driving confidence. This Evoque has travelled 154,239km and is listed as drive away with 12 month warranty included.",
  features: [
    "Leather interior",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Keyless entry",
    "Push-button start",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Cruise control",
    "Meridian sound system",
    "11 speaker stereo",
    "Subwoofer",
    "AUX input",
    "USB input",
    "MP3 decoder",
    "CD player",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "On-board computer",
    "Ambient lighting",
    "Power windows",
    "Electric heated mirrors",
    "Remote central locking",
    "Engine immobiliser",
    "Front fog lamps",
    "LED daytime running lights",
    "Rear roof spoiler",
    "Roof rails",
    "18-inch alloy wheels",
    "Space saver spare wheel",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "4x4 constant drive",
    "Traction control",
    "Electronic stability control",
    "Corner braking control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "5 airbags",
    "4 star ANCAP safety rating"
  ]
},
{
  id: "2017-land-rover-discovery-sport-sd4-hse",
  title: "2017 Land Rover Discovery Sport SD4 HSE Auto 4x4 MY18",
  price: 18285,
  kms: "86,408 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Fuji White",
  engine: "2.0L 4 Cylinder Twin Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "JHGSDF2225",
  imageLabel: "Land Rover Discovery Sport",
  image: "assets/vehicles/Range Rover Sport 2017/car_01.png",
  images: [
    "assets/vehicles/Range Rover Sport 2017/car_01.png",
    "assets/vehicles/Range Rover Sport 2017/car_02.png",
    "assets/vehicles/Range Rover Sport 2017/car_03.png",
    "assets/vehicles/Range Rover Sport 2017/car_04.png",
    "assets/vehicles/Range Rover Sport 2017/car_05.png",
    "assets/vehicles/Range Rover Sport 2017/car_06.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/land-rover-discovery-sport-2017/oag-ad-26015662/",
  description: "2017 Land Rover Discovery Sport SD4 HSE Auto 4x4 MY18 finished in Fuji White with black interior. A premium family SUV combining luxury comfort, strong twin turbo diesel performance and intelligent all-wheel drive capability. Powered by a 2.0L twin turbo diesel 4-cylinder engine paired with a 9-speed sports automatic transmission. Features include full leather interior, panoramic glass sunroof, satellite navigation, Apple CarPlay, Android Auto, reverse camera, front and rear parking sensors, electric tailgate, heated front seats, electric front seats with memory, keyless entry, push-button start, dual-zone climate control, Meridian premium sound system, lane keep assist, blind spot monitoring, autonomous emergency braking, adaptive cruise control and 19-inch alloy wheels. This Discovery Sport has travelled only 86,408km and is listed as drive away with roadworthy certificate, registration included, finance available and 12 month premium warranty included.",
  features: [
    "Full leather interior",
    "Panoramic glass sunroof",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Lane departure warning",
    "Lane keep assist",
    "Blind spot monitoring",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Adaptive cruise control",
    "Keyless entry",
    "Push-button start",
    "Electric tailgate",
    "Heated front seats",
    "Ventilated front seats",
    "Electric front seats",
    "Driver memory seat",
    "Passenger memory seat",
    "Electric lumbar support",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Meridian premium sound system",
    "11 speaker stereo",
    "Subwoofer",
    "AUX input",
    "USB input",
    "Memory card reader",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Speed limiter",
    "Automatic headlights",
    "Auto high beam",
    "LED daytime running lights",
    "LED tail lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric anti-glare mirrors",
    "Ambient interior lighting",
    "Split fold rear seats",
    "Sliding rear seat adjustment",
    "Cargo cover",
    "ISOFIX child seat anchors",
    "19-inch alloy wheels",
    "Full size alloy spare wheel",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Selectable driving modes",
    "4x4 on demand",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "7 airbags",
    "5 star ANCAP safety rating"
  ]
},
];

const services = [
  { title: "Paintless Dent Removal", text: "Remove minor dents while keeping the original paint finish where suitable." },
  { title: "Spray Painting", text: "Quality automotive paint refinishing for repaired panels and cosmetic restoration." },
  { title: "Panel Beating", text: "Dent, accident and body repair support to help your car look right again." },
  { title: "RWC Checks", text: "Roadworthy inspection support before selling, buying or re-registering a vehicle." },
  { title: "Auto Electrical Repairs", text: "Battery, electrical fault and vehicle system checks for modern vehicles." },
  { title: "Air Conditioning", text: "Car air conditioning inspection, repairs and gas refill support where required." },
  { title: "Mechanical Repairs", text: "General mechanical repairs and servicing for many makes and models." },
  { title: "Maintenance Services", text: "Regular maintenance checks to help keep your vehicle reliable and road-ready." },
  { title: "Car Body Repairs", text: "Scratch, dent and car body repair assistance for minor and major body damage." },
  { title: "European Auto Repairs", text: "Workshop support for European vehicles with experienced technicians." }
];

const reviews = [
  { name: "Hemant Khande", title: "Super quick service", text: "Got my car tyre puncture fixed. Super quick and reasonable price. I would recommend this shop." },
  { name: "Barbershop Convo", title: "Best in business", text: "Best in business, always supporting, and truthfully advising. Please go and visit the workshop!" },
  { name: "Lee Benson", title: "Good quality and prices", text: "I had my car body repair at KHG and I am so happy with the service, good quality and good prices." },
  { name: "Kanak Jagarlamudi", title: "Nice service and assistance", text: "Bought a car here, very nice service and assistance. Must check out if you want to buy a used car or car services." },
  { name: "Zale Ath", title: "Great value", text: "Great value and efficient service. Had brake pads front and rear replaced within 3 hours for a very reasonable price. Highly recommended!" },
  { name: "Sam", title: "Exceptional service", text: "Exceptional service, professional, efficient and super friendly. Very competitive with price and the workmanship is second to none." }
];
