const vehicles = [
  {
    id: "2018-toyota-corolla-ascent-sport",
    title: "2018 Toyota Corolla Ascent Sport",
    price: 15990,
    kms: "112,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Hatchback",
    colour: "White",
    engine: "1.8L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG001",
    imageLabel: "Toyota Corolla",
    image: "",
    images: [],
    description: "Dummy listing for 2018 Toyota Corolla Ascent Sport. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2016-mazda-cx-5-maxx-sport",
    title: "2016 Mazda CX-5 Maxx Sport",
    price: 18500,
    kms: "138,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "Grey",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG002",
    imageLabel: "Mazda CX-5",
    image: "",
    images: [],
    description: "Dummy listing for 2016 Mazda CX-5 Maxx Sport. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2019-hyundai-i30-active",
    title: "2019 Hyundai i30 Active",
    price: 16990,
    kms: "92,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Hatchback",
    colour: "Silver",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG003",
    imageLabel: "Hyundai i30",
    image: "",
    images: [],
    description: "Dummy listing for 2019 Hyundai i30 Active. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2017-volkswagen-golf-comfortline",
    title: "2017 Volkswagen Golf Comfortline",
    price: 14990,
    kms: "121,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Hatchback",
    colour: "Black",
    engine: "1.4L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG004",
    imageLabel: "Volkswagen Golf",
    image: "",
    images: [],
    description: "Dummy listing for 2017 Volkswagen Golf Comfortline. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2020-kia-cerato-sport",
    title: "2020 Kia Cerato Sport",
    price: 21990,
    kms: "76,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Sedan",
    colour: "Blue",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG005",
    imageLabel: "Kia Cerato",
    image: "",
    images: [],
    description: "Dummy listing for 2020 Kia Cerato Sport. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-nissan-x-trail-st",
    title: "2018 Nissan X-Trail ST",
    price: 19990,
    kms: "118,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "White",
    engine: "2.5L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG006",
    imageLabel: "Nissan X-Trail",
    image: "",
    images: [],
    description: "Dummy listing for 2018 Nissan X-Trail ST. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2017-toyota-camry-altise",
    title: "2017 Toyota Camry Altise",
    price: 17990,
    kms: "132,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Sedan",
    colour: "Silver",
    engine: "2.5L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG007",
    imageLabel: "Toyota Camry",
    image: "",
    images: [],
    description: "Dummy listing for 2017 Toyota Camry Altise. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2019-mitsubishi-asx-ls",
    title: "2019 Mitsubishi ASX LS",
    price: 20990,
    kms: "88,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "White",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG008",
    imageLabel: "Mitsubishi ASX",
    image: "",
    images: [],
    description: "Dummy listing for 2019 Mitsubishi ASX LS. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2016-holden-commodore-sv6",
    title: "2016 Holden Commodore SV6",
    price: 22990,
    kms: "145,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Sedan",
    colour: "Red",
    engine: "3.6L V6",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG009",
    imageLabel: "Holden Commodore",
    image: "",
    images: [],
    description: "Dummy listing for 2016 Holden Commodore SV6. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2021-mg-zs-excite",
    title: "2021 MG ZS Excite",
    price: 18990,
    kms: "64,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "Black",
    engine: "1.5L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG010",
    imageLabel: "MG ZS",
    image: "",
    images: [],
    description: "Dummy listing for 2021 MG ZS Excite. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2015-honda-civic-vti-l",
    title: "2015 Honda Civic VTi-L",
    price: 13990,
    kms: "156,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Sedan",
    colour: "Grey",
    engine: "1.8L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG011",
    imageLabel: "Honda Civic",
    image: "",
    images: [],
    description: "Dummy listing for 2015 Honda Civic VTi-L. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2020-toyota-rav4-gx",
    title: "2020 Toyota RAV4 GX",
    price: 32990,
    kms: "82,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "White",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG012",
    imageLabel: "Toyota RAV4",
    image: "",
    images: [],
    description: "Dummy listing for 2020 Toyota RAV4 GX. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-ford-ranger-xl",
    title: "2018 Ford Ranger XL",
    price: 29990,
    kms: "164,000 km",
    transmission: "Automatic",
    fuel: "Diesel",
    warranty: "Warranty option",
    body: "Ute",
    colour: "White",
    engine: "3.2L Turbo Diesel",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG013",
    imageLabel: "Ford Ranger",
    image: "",
    images: [],
    description: "Dummy listing for 2018 Ford Ranger XL. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Tow bar option", "Bluetooth", "Cruise control", "Tray/utility body", "Air conditioning", "Service history"]
  },
  {
    id: "2017-subaru-forester-2-5i",
    title: "2017 Subaru Forester 2.5i",
    price: 18990,
    kms: "127,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "Blue",
    engine: "2.5L Boxer",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG014",
    imageLabel: "Subaru Forester",
    image: "",
    images: [],
    description: "Dummy listing for 2017 Subaru Forester 2.5i. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2019-kia-sportage-si",
    title: "2019 Kia Sportage Si",
    price: 22990,
    kms: "101,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Silver",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG015",
    imageLabel: "Kia Sportage",
    image: "",
    images: [],
    description: "Dummy listing for 2019 Kia Sportage Si. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2016-mercedes-benz-c200",
    title: "2016 Mercedes-Benz C200",
    price: 26990,
    kms: "116,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Sedan",
    colour: "Black",
    engine: "2.0L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG016",
    imageLabel: "Mercedes-Benz C200",
    image: "",
    images: [],
    description: "Dummy listing for 2016 Mercedes-Benz C200. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-bmw-320i-sport-line",
    title: "2018 BMW 320i Sport Line",
    price: 28990,
    kms: "109,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Sedan",
    colour: "White",
    engine: "2.0L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG017",
    imageLabel: "BMW 320i",
    image: "",
    images: [],
    description: "Dummy listing for 2018 BMW 320i Sport Line. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2017-audi-a3-attraction",
    title: "2017 Audi A3 Attraction",
    price: 21990,
    kms: "119,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Sedan",
    colour: "Grey",
    engine: "1.4L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG018",
    imageLabel: "Audi A3",
    image: "",
    images: [],
    description: "Dummy listing for 2017 Audi A3 Attraction. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2020-hyundai-tucson-active",
    title: "2020 Hyundai Tucson Active",
    price: 24990,
    kms: "79,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "White",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG019",
    imageLabel: "Hyundai Tucson",
    image: "",
    images: [],
    description: "Dummy listing for 2020 Hyundai Tucson Active. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2015-toyota-hilux-sr",
    title: "2015 Toyota Hilux SR",
    price: 27990,
    kms: "188,000 km",
    transmission: "Automatic",
    fuel: "Diesel",
    warranty: "Warranty available",
    body: "Ute",
    colour: "Silver",
    engine: "2.8L Turbo Diesel",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG020",
    imageLabel: "Toyota Hilux",
    image: "",
    images: [],
    description: "Dummy listing for 2015 Toyota Hilux SR. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Tow bar option", "Bluetooth", "Cruise control", "Tray/utility body", "Air conditioning", "Service history"]
  },
  {
    id: "2021-haval-h6-premium",
    title: "2021 Haval H6 Premium",
    price: 21990,
    kms: "58,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Blue",
    engine: "2.0L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG021",
    imageLabel: "Haval H6",
    image: "",
    images: [],
    description: "Dummy listing for 2021 Haval H6 Premium. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-mazda-3-neo-sport",
    title: "2018 Mazda 3 Neo Sport",
    price: 15990,
    kms: "124,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Hatchback",
    colour: "Red",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG022",
    imageLabel: "Mazda 3",
    image: "",
    images: [],
    description: "Dummy listing for 2018 Mazda 3 Neo Sport. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2019-nissan-qashqai-st",
    title: "2019 Nissan Qashqai ST",
    price: 20990,
    kms: "95,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Grey",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG023",
    imageLabel: "Nissan Qashqai",
    image: "",
    images: [],
    description: "Dummy listing for 2019 Nissan Qashqai ST. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2016-suzuki-swift-gl",
    title: "2016 Suzuki Swift GL",
    price: 11990,
    kms: "134,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Hatchback",
    colour: "White",
    engine: "1.4L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG024",
    imageLabel: "Suzuki Swift",
    image: "",
    images: [],
    description: "Dummy listing for 2016 Suzuki Swift GL. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2020-volkswagen-tiguan-110tsi",
    title: "2020 Volkswagen Tiguan 110TSI",
    price: 29990,
    kms: "84,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Black",
    engine: "1.4L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG025",
    imageLabel: "Volkswagen Tiguan",
    image: "",
    images: [],
    description: "Dummy listing for 2020 Volkswagen Tiguan 110TSI. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-holden-trax-ls",
    title: "2018 Holden Trax LS",
    price: 14990,
    kms: "106,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "Orange",
    engine: "1.4L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG026",
    imageLabel: "Holden Trax",
    image: "",
    images: [],
    description: "Dummy listing for 2018 Holden Trax LS. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2017-ford-focus-trend",
    title: "2017 Ford Focus Trend",
    price: 13990,
    kms: "118,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Hatchback",
    colour: "Silver",
    engine: "1.5L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG027",
    imageLabel: "Ford Focus",
    image: "",
    images: [],
    description: "Dummy listing for 2017 Ford Focus Trend. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    carsalesUrl: "https://www.carsales.com.au/cars/details/2010-ford-falcon-xr6-fg-auto/OAG-AD-25830603/",
    externalListing: {
      label: "Official Carsales Listing",
      url: "https://www.carsales.com.au/cars/details/2010-ford-falcon-xr6-fg-auto/OAG-AD-25830603/",
      text: "This vehicle is also advertised online. Open the Carsales listing for the live advertisement details."
    },
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2019-toyota-yaris-ascent",
    title: "2019 Toyota Yaris Ascent",
    price: 15990,
    kms: "89,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Hatchback",
    colour: "White",
    engine: "1.3L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG028",
    imageLabel: "Toyota Yaris",
    image: "",
    images: [],
    description: "Dummy listing for 2019 Toyota Yaris Ascent. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    carsalesUrl: "https://www.carsales.com.au/cars/details/2010-ford-falcon-xr6-fg-auto/OAG-AD-25830603/",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2016-jeep-cherokee-longitude",
    title: "2016 Jeep Cherokee Longitude",
    price: 17990,
    kms: "139,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Black",
    engine: "3.2L V6",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG029",
    imageLabel: "Jeep Cherokee",
    image: "",
    images: [],
    description: "Dummy listing for 2016 Jeep Cherokee Longitude. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2021-mitsubishi-outlander-es",
    title: "2021 Mitsubishi Outlander ES",
    price: 27990,
    kms: "72,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "Silver",
    engine: "2.4L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG030",
    imageLabel: "Mitsubishi Outlander",
    image: "",
    images: [],
    description: "Dummy listing for 2021 Mitsubishi Outlander ES. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  }
];

const services = [
  { title: "Paintless Dent Removal", text: "Remove minor dents while keeping the original paint finish where suitable." },
  { title: "Spray Painting", text: "Quality automotive paint refinishing for repaired panels and cosmetic restoration." },
  { title: "Panel Beating", text: "Dent, accident and body repair support to help your car look right again." },
  { title: "RWC Checks", text: "Roadworthy inspection support before selling, buying or re-registering a vehicle." },
  { title: "Auto Electrical Repairs", text: "Battery, electrical fault and vehicle system checks for modern vehicles." },
  { title: "Air Conditioning", text: "Car air conditioning inspection, repairs and gas refill support where required." },
  { title: "Mechanical Repairs", text: "General mechanical repairs and servicing for many makes and models." },
  { title: "Maintenance Services", text: "Regular maintenance checks to help keep your vehicle reliable and road-ready." },
  { title: "Car Body Repairs", text: "Scratch, dent and car body repair assistance for minor and major body damage." },
  { title: "European Auto Repairs", text: "Workshop support for European vehicles with experienced technicians." }
];

const reviews = [
  { name: "Hemant Khande", title: "Super quick service", text: "Got my car tyre puncture fixed. Super quick and reasonable price. I would recommend this shop." },
  { name: "Barbershop Convo", title: "Best in business", text: "Best in business, always supporting, and truthfully advising. Please go and visit the workshop!" },
  { name: "Lee Benson", title: "Good quality and prices", text: "I had my car body repair at KHG and I am so happy with the service, good quality and good prices." },
  { name: "Kanak Jagarlamudi", title: "Nice service and assistance", text: "Bought a car here, very nice service and assistance. Must check out if you want to buy a used car or car services." },
  { name: "Zale Ath", title: "Great value", text: "Great value and efficient service. Had brake pads front and rear replaced within 3 hours for a very reasonable price. Highly recommended!" },
  { name: "Sam", title: "Exceptional service", text: "Exceptional service, professional, efficient and super friendly. Very competitive with price and the workmanship is second to none." }
];
