const vehicles = [
  {
  id: "2015-bmw-x5-xdrive30d",
  title: "2015 BMW X5 xDrive30d F15 Auto 4x4",
  price: 21990,
  kms: "157,801 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "1 year premium warranty included",
  body: "SUV",
  colour: "Alpine White",
  engine: "3.0L 6 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGUSEDBMWX5WHITE",
  imageLabel: "BMW X5",
  image: "assets/vehicles/BMW X5 2015/car_01.png",
  images: [
    "assets/vehicles/BMW X5 2015/car_01.png",
    "assets/vehicles/BMW X5 2015/car_02.png",
    "assets/vehicles/BMW X5 2015/car_03.png",
    "assets/vehicles/BMW X5 2015/car_04.png",
    "assets/vehicles/BMW X5 2015/car_05.png",
    "assets/vehicles/BMW X5 2015/car_06.png",
    "assets/vehicles/BMW X5 2015/car_07.png",
    "assets/vehicles/BMW X5 2015/car_08.png",
    "assets/vehicles/BMW X5 2015/car_09.png",
    "assets/vehicles/BMW X5 2015/car_10.png",
    "assets/vehicles/BMW X5 2015/car_11.png",
    "assets/vehicles/BMW X5 2015/car_12.png",
    "assets/vehicles/BMW X5 2015/car_13.png",
    "assets/vehicles/BMW X5 2015/car_14.png",
    "assets/vehicles/BMW X5 2015/car_15.png",
    "assets/vehicles/BMW X5 2015/car_16.png",
    "assets/vehicles/BMW X5 2015/car_17.png",
    "assets/vehicles/BMW X5 2015/car_18.png",
    "assets/vehicles/BMW X5 2015/car_19.png",
    "assets/vehicles/BMW X5 2015/car_20.png",
    "assets/vehicles/BMW X5 2015/car_21.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-x5-2015/oag-ad-25730224/",
  description: "2015 BMW X5 xDrive30d F15 Auto 4x4 finished in Alpine White with black interior. A premium diesel AWD luxury SUV combining strong performance, comfort, space and excellent long-distance efficiency. Powered by a 3.0L turbo diesel 6-cylinder engine paired with an 8-speed sports automatic transmission and xDrive 4x4 system, producing 190kW and 560Nm with combined fuel consumption of 5.9L/100km. Features include full BMW service history, leather interior, 360-degree camera system, reverse camera, front and rear parking sensors, satellite navigation, Bluetooth, low-speed AEB, lane departure warning, forward collision warning, dual-zone climate control, keyless start, push-button start, electric seats with driver memory, electric tailgate, head-up display, rain-sensing wipers, Bi-Xenon headlights, 19-inch alloy wheels and premium 9-speaker audio. This X5 has travelled 157,801km and is listed as drive away with roadworthy certificate provided and 1 year premium warranty included.",
  features: [
    "Full BMW service history",
    "Leather interior",
    "360 degree camera",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Bluetooth",
    "GPS satellite navigation",
    "Low-speed AEB",
    "Lane departure warning",
    "Forward collision warning",
    "Driver fatigue warning",
    "Dual-zone climate control",
    "Keyless start",
    "Push-button start",
    "Electric front seats",
    "Driver memory seat",
    "Head-up display",
    "Electric tailgate",
    "Rain-sensing wipers",
    "Bi-Xenon headlights",
    "Automatic headlights",
    "LED fog lights",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Premium 9 speaker stereo",
    "USB/AUX input",
    "19-inch alloy wheels",
    "xDrive AWD",
    "Excellent fuel economy",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Hill descent control",
    "Hill holder",
    "6 airbags"
  ]
},
  {
    id: "2012 Mercedes-Benz M-Class ML63 AMG Auto",
    title: "2012 Mercedes-Benz M-Class ML63 AMG Auto",
    price: 29888,
    kms: "143,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Wagon",
    colour: "Black",
    engine: "5.5L, 8 cylinders, Twin Turbo Intercooled",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG004",
    imageLabel: "Mercedes-Benz M-Class",
    image: "",
    images: [
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_01.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_02.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_03.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_04.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_05.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_06.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_07.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_08.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_09.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_10.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_11.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_12.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_13.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_14.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_15.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_16.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_17.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_18.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_19.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_20.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_21.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_22.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_23.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_24.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_25.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_26.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_27.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_28.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_29.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_30.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_31.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_32.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_33.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_34.png",
  "assets/vehicles/Mercedes Benz M 2012 Wagon/car_35.png"
],
    description: "2012 Mercedes-Benz M-Class ML63 AMG Auto 4x4 finished in Obsidian Black with black interior. Powered by a 5.5L twin-turbo V8 AMG engine producing 386kW and 700Nm, paired with a 7-speed SPEEDSHIFT automatic and 4MATIC all-wheel drive. Features include sunroof, leather interior with electric seats, satellite navigation, reverse camera, parking sensors, Bluetooth, premium sound system, keyless entry, push-button start, AMG alloy wheels and strong AMG performance luxury. Dealer listing shows 143,000km, roadworthy certificate included, registered and ready to drive away, with 12-month premium warranty available.",
    carsalesUrl: "https://www.carsales.com.au/cars/details/mercedes-benz-m-class-2012/oag-ad-25759848/?_ga=2.17678523.308244152.1778121915-1659496573.1769044340",
    externalListing: {
      label: "Official Carsales Listing",
      url: "https://www.carsales.com.au/cars/details/mercedes-benz-m-class-2012/oag-ad-25759848/?_ga=2.17678523.308244152.1778121915-1659496573.1769044340",
      text: "This vehicle is also advertised online. Open the Carsales listing for the live advertisement details."
    },
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Sunroof","AEB (Full/VRU)","Traction and/or Stability Control"]
  },
  {
  id: "2014-mercedes-benz-b-class-b250",
  title: "2014 Mercedes-Benz B-Class B250 Auto",
  price: 9999,
  kms: "175,326 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "1 year warranty included",
  body: "Hatchback",
  colour: "Cosmos Black",
  engine: "2.0L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGUSEDMERCB250",
  imageLabel: "Mercedes-Benz B-Class",

  images: [
    "assets/vehicles/Mercedes Benz B Class 2014/car_01.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_02.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_03.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_04.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_05.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_06.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_07.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_08.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_09.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_10.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_11.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_12.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_13.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_14.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_15.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_16.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_17.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_18.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_19.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_20.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_21.png",
    "assets/vehicles/Mercedes Benz B Class 2014/car_22.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/mercedes-benz-b-class-2014/oag-ad-25730218/",
  description: "2014 Mercedes-Benz B-Class B250 Auto finished in Cosmos Black with black interior. A stylish and practical turbocharged Mercedes hatch offering strong performance, luxury comfort and everyday usability. Powered by a 2.0L turbo petrol engine with a 7-speed sports automatic dual clutch transmission, producing 155kW and 350Nm. Features include full Mercedes-Benz service history, leather interior, reverse camera, front and rear parking sensors, Bluetooth, GPS satellite navigation, cruise control, dual-zone climate control, automatic headlights, Bi-Xenon headlights, LED daytime running lights, rain-sensing wipers, electric folding mirrors, 18-inch alloy wheels, paddle shifters and a 5-star ANCAP safety rating. This B250 has travelled 175,326km and is listed as drive away with roadworthy certificate provided, long registration until January 2027 and 1 year warranty included.",
  features: [
    "Full Mercedes-Benz service history",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Bluetooth",
    "GPS satellite navigation",
    "Cruise control",
    "Dual-zone climate control",
    "Automatic headlights",
    "Bi-Xenon headlights",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Leather interior",
    "Electric lumbar support",
    "Multi-function steering wheel",
    "Paddle shifters",
    "18-inch alloy wheels",
    "Sport styling",
    "6 speaker stereo",
    "USB/AUX input",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Hill holder",
    "9 airbags",
    "5 star ANCAP safety rating"
  ]
},
  {
  id: "2015-toyota-camry-altise",
  title: "2015 Toyota Camry Altise Auto",
  price: 19327,
  kms: "55,864 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month warranty included",
  body: "Sedan",
  colour: "Graphite",
  engine: "2.5L 4 Cylinder Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGTOYOTACAMRY15",
  imageLabel: "Toyota Camry Altise",
  image: "assets/vehicles/Toyota Camry Altise 2015/car_01.png",
  images: [
    "assets/vehicles/Toyota Camry Altise 2015/car_01.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_02.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_03.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_04.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_05.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_06.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_07.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_08.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_09.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_10.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_11.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_12.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_13.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_14.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_15.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_16.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_17.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_18.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_19.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_20.png",
    "assets/vehicles/Toyota Camry Altise 2015/car_21.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/toyota-camry-2015/oag-ad-25759310/",
  description: "2015 Toyota Camry Altise Auto finished in Graphite with black interior. A reliable and spacious sedan powered by a smooth 2.5L 4-cylinder petrol engine paired with a 6-speed sports automatic transmission. Features include reverse camera, Bluetooth connectivity, cruise control, automatic headlights, air conditioning, power windows, remote central locking, multi-function steering wheel, 6-speaker stereo, USB/AUX input, 16-inch alloy wheels and a spacious 5-seat interior. This Camry has travelled only 55,864km and is listed as drive away with roadworthy certificate provided, registration until November 2026 and 12-month warranty included.",
  features: [
    "Low kilometres",
    "Reverse camera",
    "Bluetooth",
    "Cruise control",
    "Automatic headlights",
    "Air conditioning",
    "Power windows",
    "Remote central locking",
    "Multi-function steering wheel",
    "6 speaker stereo",
    "USB/AUX input",
    "16-inch alloy wheels",
    "Spacious interior",
    "Excellent fuel economy",
    "Toyota reliability",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "7 airbags",
    "5 star ANCAP safety rating"
  ]
},
  {
  id: "2015-nissan-qashqai-st",
  title: "2015 Nissan QASHQAI ST J11 Auto",
  price: 12999,
  kms: "151,335 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12–36 month extended warranty options available",
  body: "SUV",
  colour: "Ivory Pearl",
  engine: "2.0L 4 Cylinder Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOQASHQAI",
  imageLabel: "Nissan QASHQAI",
  image: "assets/vehicles/Nissan Qashqai 2015/car_01.png",
  images: [
    "assets/vehicles/Nissan Qashqai 2015/car_01.png",
    "assets/vehicles/Nissan Qashqai 2015/car_02.png",
    "assets/vehicles/Nissan Qashqai 2015/car_03.png",
    "assets/vehicles/Nissan Qashqai 2015/car_04.png",
    "assets/vehicles/Nissan Qashqai 2015/car_05.png",
    "assets/vehicles/Nissan Qashqai 2015/car_06.png",
    "assets/vehicles/Nissan Qashqai 2015/car_07.png",
    "assets/vehicles/Nissan Qashqai 2015/car_08.png",
    "assets/vehicles/Nissan Qashqai 2015/car_09.png",
    "assets/vehicles/Nissan Qashqai 2015/car_10.png",
    "assets/vehicles/Nissan Qashqai 2015/car_11.png",
    "assets/vehicles/Nissan Qashqai 2015/car_12.png",
    "assets/vehicles/Nissan Qashqai 2015/car_13.png",
    "assets/vehicles/Nissan Qashqai 2015/car_14.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/nissan-qashqai-2015/oag-ad-25806740/",
  description: "2015 Nissan QASHQAI ST J11 Auto finished in Ivory Pearl with black interior. A reliable, economical and practical 5-seat SUV, ideal for daily driving, first car buyers or small families. Powered by a 2.0L 4-cylinder petrol engine with automatic CVT transmission and front-wheel drive, offering smooth driving and excellent fuel economy of 6.9L/100km combined. Features include reverse camera, Bluetooth connectivity, cruise control, air conditioning, power windows, multi-function steering wheel, USB/AUX input, 17-inch alloy wheels, LED daytime running lights, remote central locking and a spacious 430L boot. This QASHQAI has travelled 151,335km and is listed as drive away with roadworthy certificate included, registration until January 2027 and 12–36 month extended warranty options available.",
  features: [
    "Reverse camera",
    "Bluetooth",
    "Cruise control",
    "Air conditioning",
    "Power windows",
    "Multi-function steering wheel",
    "USB/AUX input",
    "4 speaker stereo",
    "17-inch alloy wheels",
    "LED daytime running lights",
    "Remote central locking",
    "Electric mirrors",
    "Split fold rear seats",
    "Spacious 430L boot",
    "Excellent fuel economy",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Hill holder",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
  {
  id: "2015-mazda-cx-5-grand-touring",
  title: "2015 Mazda CX-5 Grand Touring KE Series 2 Auto AWD",
  price: 15900,
  kms: "120,637 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Crystal White Pearl",
  engine: "2.2L 4 Cylinder Twin Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOCX5GT",
  imageLabel: "Mazda CX-5",
  image: "assets/vehicles/Mazda CX5 2015/car_01.png",
  images: [
    "assets/vehicles/Mazda CX5 2015/car_01.png",
    "assets/vehicles/Mazda CX5 2015/car_02.png",
    "assets/vehicles/Mazda CX5 2015/car_03.png",
    "assets/vehicles/Mazda CX5 2015/car_04.png",
    "assets/vehicles/Mazda CX5 2015/car_05.png",
    "assets/vehicles/Mazda CX5 2015/car_06.png",
    "assets/vehicles/Mazda CX5 2015/car_07.png",
    "assets/vehicles/Mazda CX5 2015/car_08.png",
    "assets/vehicles/Mazda CX5 2015/car_09.png",
    "assets/vehicles/Mazda CX5 2015/car_10.png",
    "assets/vehicles/Mazda CX5 2015/car_11.png",
    "assets/vehicles/Mazda CX5 2015/car_12.png",
    "assets/vehicles/Mazda CX5 2015/car_13.png",
    "assets/vehicles/Mazda CX5 2015/car_14.png",
    "assets/vehicles/Mazda CX5 2015/car_15.png",
    "assets/vehicles/Mazda CX5 2015/car_16.png",
    "assets/vehicles/Mazda CX5 2015/car_17.png",
    "assets/vehicles/Mazda CX5 2015/car_18.png",
    "assets/vehicles/Mazda CX5 2015/car_19.png",
    "assets/vehicles/Mazda CX5 2015/car_20.png",
    "assets/vehicles/Mazda CX5 2015/car_21.png",
    "assets/vehicles/Mazda CX5 2015/car_22.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/mazda-cx-5-2015/oag-ad-25806588/",
  description: "2015 Mazda CX-5 Grand Touring KE Series 2 Auto AWD finished in Crystal White Pearl with black interior. A well-presented and feature-packed SUV offering a great mix of comfort, performance, practicality and fuel efficiency. Powered by a 2.2L twin turbo diesel engine with a 6-speed SKYACTIV-Drive automatic transmission and AWD capability, producing 129kW and 420Nm with excellent combined fuel economy of 5.7L/100km. Features include leather interior, electric seats with driver memory, sunroof, reverse camera, front and rear parking sensors, Bluetooth, GPS satellite navigation, cruise control, dual-zone climate control, keyless entry, push-button start, LED headlights, rain-sensing wipers, Bose-style premium 9-speaker audio, 19-inch alloy wheels and a 5-star ANCAP safety rating. This CX-5 has travelled 120,637km and is listed as drive away with roadworthy certificate included, 3 months registration included and 12-month warranty included.",
  features: [
    "Full service history",
    "Sunroof",
    "Leather interior",
    "Electric seats",
    "Driver memory seat",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Bluetooth",
    "GPS satellite navigation",
    "Cruise control",
    "Dual-zone climate control",
    "Keyless entry",
    "Push-button start",
    "Automatic headlights",
    "LED headlights",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Electric anti-glare mirror",
    "Power windows",
    "Multi-function steering wheel",
    "9 speaker stereo",
    "USB/AUX input",
    "19-inch alloy wheels",
    "AWD",
    "Excellent fuel economy",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Hill holder",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
  {
  id: "2014-jeep-grand-cherokee-overland",
  title: "2014 Jeep Grand Cherokee Overland Auto 4x4 MY15",
  price: 17888,
  kms: "137,271 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "1 year premium warranty included",
  body: "SUV",
  colour: "Maximum Steel",
  engine: "3.0L V6 Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGJEEPGCHOVERLND",
  imageLabel: "Jeep Grand Cherokee",
  image: "assets/vehicles/Jeep Grand Cherokee 2014/car_01.png",
  images: [
    "assets/vehicles/Jeep Grand Cherokee 2014/car_01.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_02.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_03.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_04.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_05.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_06.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_07.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_08.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_09.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_10.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_11.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_12.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_13.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_14.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_15.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_16.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_17.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_18.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_19.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_20.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_21.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_22.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_23.png",
    "assets/vehicles/Jeep Grand Cherokee 2014/car_24.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/jeep-grand-cherokee-2014/oag-ad-25730228/",
  description: "2014 Jeep Grand Cherokee Overland Auto 4x4 MY15 finished in Maximum Steel with black interior. A top-of-the-range luxury diesel SUV powered by a strong and efficient 3.0L turbo diesel V6 engine paired with an 8-speed sports automatic transmission and 4x4 capability. Features include premium leather interior, heated and ventilated front seats, panoramic sunroof, satellite navigation, Bluetooth, reverse camera, front and rear parking sensors, blind spot monitoring, keyless entry, push-button start, premium 9-speaker sound system with subwoofer, electric tailgate, alloy wheels, dual-zone climate control and a 5-star ANCAP safety rating. This Grand Cherokee has travelled 137,271km and is listed as drive away with roadworthy certificate provided and 1 year premium warranty included.",
  features: [
    "Panoramic sunroof",
    "Premium leather interior",
    "Heated front seats",
    "Ventilated front seats",
    "Electric front seats",
    "Driver memory seat",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Blind spot monitoring",
    "Keyless entry",
    "Push-button start",
    "Dual-zone climate control",
    "Premium 9 speaker sound system",
    "Subwoofer",
    "Digital radio",
    "USB/AUX input",
    "Electric tailgate",
    "Electric folding mirrors",
    "Heated mirrors",
    "Bi-Xenon headlights",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Cruise control",
    "4x4 capability",
    "Hill holder",
    "Trailer sway control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "5 star ANCAP safety rating"
  ]
},
  {
  id: "2016-mazda-cx-5-maxx-sport",
  title: "2016 Mazda CX-5 Maxx Sport KE Series 2 Auto i-ACTIV AWD",
  price: 15990,
  kms: "117,357 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Meteor Grey",
  engine: "2.2L 4 Cylinder Twin Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGMAZDACX5GREY",
  imageLabel: "Mazda CX-5",
  image: "assets/vehicles/Mazda CX5 2016/car_01.png",
  images: [
    "assets/vehicles/Mazda CX5 2016/car_01.png",
    "assets/vehicles/Mazda CX5 2016/car_02.png",
    "assets/vehicles/Mazda CX5 2016/car_03.png",
    "assets/vehicles/Mazda CX5 2016/car_04.png",
    "assets/vehicles/Mazda CX5 2016/car_05.png",
    "assets/vehicles/Mazda CX5 2016/car_06.png",
    "assets/vehicles/Mazda CX5 2016/car_07.png",
    "assets/vehicles/Mazda CX5 2016/car_08.png",
    "assets/vehicles/Mazda CX5 2016/car_09.png",
    "assets/vehicles/Mazda CX5 2016/car_10.png",
    "assets/vehicles/Mazda CX5 2016/car_11.png",
    "assets/vehicles/Mazda CX5 2016/car_12.png",
    "assets/vehicles/Mazda CX5 2016/car_13.png",
    "assets/vehicles/Mazda CX5 2016/car_14.png",
    "assets/vehicles/Mazda CX5 2016/car_15.png",
    "assets/vehicles/Mazda CX5 2016/car_16.png",
    "assets/vehicles/Mazda CX5 2016/car_17.png",
    "assets/vehicles/Mazda CX5 2016/car_18.png",
    "assets/vehicles/Mazda CX5 2016/car_19.png",
    "assets/vehicles/Mazda CX5 2016/car_20.png",
    "assets/vehicles/Mazda CX5 2016/car_21.png",
    "assets/vehicles/Mazda CX5 2016/car_22.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/mazda-cx-5-2016/oag-ad-25758025/",
  description: "2016 Mazda CX-5 Maxx Sport KE Series 2 Auto i-ACTIV AWD finished in Meteor Grey with black interior. A clean, practical and fuel-efficient diesel SUV, ideal for daily driving, family use or long-distance trips. Powered by a 2.2L twin turbo diesel engine paired with a 6-speed SKYACTIV-Drive automatic transmission and i-ACTIV AWD, producing 129kW and 420Nm with excellent combined fuel economy of 5.7L/100km. Features include Bluetooth connectivity, reverse camera, GPS satellite navigation, blind spot monitoring, low-speed AEB, cruise control, dual-zone climate control, keyless start, rain-sensing wipers, automatic headlights, alloy wheels, spacious interior and a 5-star ANCAP safety rating. This CX-5 has travelled 117,357km and is listed as drive away with roadworthy certificate provided, registration until May 2026 and 12 month premium warranty included.",
  features: [
    "Bluetooth",
    "Reverse camera",
    "GPS satellite navigation",
    "Blind spot monitoring",
    "Low-speed AEB",
    "Cruise control",
    "Dual-zone climate control",
    "Keyless start",
    "Push-button start",
    "Rain-sensing wipers",
    "Automatic headlights",
    "Power windows",
    "Electric mirrors",
    "Multi-function steering wheel",
    "6 speaker stereo",
    "USB/AUX input",
    "17-inch alloy wheels",
    "Spacious interior",
    "i-ACTIV AWD",
    "Excellent fuel economy",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Hill holder",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
  {
  id: "2013-bmw-x1-sdrive18d",
  title: "2013 BMW X1 sDrive18d E84 LCI Auto MY14",
  price: 9999,
  kms: "115,260 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Alpine White",
  engine: "2.0L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOBMWX1",
  imageLabel: "BMW X1",
  image: "assets/vehicles/BMW X1 2013/car_01.png",
  images: [
    "assets/vehicles/BMW X1 2013/car_01.png",
    "assets/vehicles/BMW X1 2013/car_02.png",
    "assets/vehicles/BMW X1 2013/car_03.png",
    "assets/vehicles/BMW X1 2013/car_04.png",
    "assets/vehicles/BMW X1 2013/car_05.png",
    "assets/vehicles/BMW X1 2013/car_06.png",
    "assets/vehicles/BMW X1 2013/car_07.png",
    "assets/vehicles/BMW X1 2013/car_08.png",
    "assets/vehicles/BMW X1 2013/car_09.png",
    "assets/vehicles/BMW X1 2013/car_10.png",
    "assets/vehicles/BMW X1 2013/car_11.png",
    "assets/vehicles/BMW X1 2013/car_12.png",
    "assets/vehicles/BMW X1 2013/car_13.png",
    "assets/vehicles/BMW X1 2013/car_14.png",
    "assets/vehicles/BMW X1 2013/car_15.png",
    "assets/vehicles/BMW X1 2013/car_16.png",
    "assets/vehicles/BMW X1 2013/car_17.png",
    "assets/vehicles/BMW X1 2013/car_18.png",
    "assets/vehicles/BMW X1 2013/car_19.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-x1-2013/oag-ad-25806679/",
  description: "2013 BMW X1 sDrive18d E84 LCI Auto MY14 finished in Alpine White with black interior. A great value luxury diesel SUV offering BMW performance, everyday practicality and excellent fuel economy. Powered by a 2.0L turbo diesel 4-cylinder engine paired with an 8-speed Steptronic sports automatic transmission and rear-wheel drive, producing 105kW and 320Nm with combined fuel consumption of just 5.0L/100km. Features include leather-look interior, Bluetooth connectivity, GPS satellite navigation, rear parking sensors, cruise control with brake function, automatic headlights, rain-sensing wipers, dual-zone climate control, push-button start, power windows, 17-inch alloy wheels, roof rails, multi-function steering wheel, USB/AUX input and a 5-star ANCAP safety rating. This X1 has travelled 115,260km and is listed as drive away with roadworthy certificate included, registered and ready to drive, with 12 month warranty included.",
  features: [
    "Bluetooth",
    "GPS satellite navigation",
    "Rear parking sensors",
    "Cruise control",
    "Automatic headlights",
    "Rain-sensing wipers",
    "Dual-zone climate control",
    "Push-button start",
    "Leather-look interior",
    "Power windows",
    "Multi-function steering wheel",
    "5 speaker stereo",
    "USB/AUX input",
    "CD player",
    "17-inch alloy wheels",
    "Roof rails",
    "Split fold rear seats",
    "Excellent fuel economy",
    "Rear wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Hill holder",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
  {
    id: "2020-toyota-rav4-gx",
    title: "2020 Toyota RAV4 GX",
    price: 32990,
    kms: "82,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "White",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG012",
    imageLabel: "Toyota RAV4",
    image: "",
    images: [],
    description: "Dummy listing for 2020 Toyota RAV4 GX. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-ford-ranger-xl",
    title: "2018 Ford Ranger XL",
    price: 29990,
    kms: "164,000 km",
    transmission: "Automatic",
    fuel: "Diesel",
    warranty: "Warranty option",
    body: "Ute",
    colour: "White",
    engine: "3.2L Turbo Diesel",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG013",
    imageLabel: "Ford Ranger",
    image: "",
    images: [],
    description: "Dummy listing for 2018 Ford Ranger XL. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Tow bar option", "Bluetooth", "Cruise control", "Tray/utility body", "Air conditioning", "Service history"]
  },
  {
    id: "2017-subaru-forester-2-5i",
    title: "2017 Subaru Forester 2.5i",
    price: 18990,
    kms: "127,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "Blue",
    engine: "2.5L Boxer",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG014",
    imageLabel: "Subaru Forester",
    image: "",
    images: [],
    description: "Dummy listing for 2017 Subaru Forester 2.5i. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2019-kia-sportage-si",
    title: "2019 Kia Sportage Si",
    price: 22990,
    kms: "101,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Silver",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG015",
    imageLabel: "Kia Sportage",
    image: "",
    images: [],
    description: "Dummy listing for 2019 Kia Sportage Si. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2016-mercedes-benz-c200",
    title: "2016 Mercedes-Benz C200",
    price: 26990,
    kms: "116,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Sedan",
    colour: "Black",
    engine: "2.0L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG016",
    imageLabel: "Mercedes-Benz C200",
    image: "",
    images: [],
    description: "Dummy listing for 2016 Mercedes-Benz C200. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-bmw-320i-sport-line",
    title: "2018 BMW 320i Sport Line",
    price: 28990,
    kms: "109,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Sedan",
    colour: "White",
    engine: "2.0L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG017",
    imageLabel: "BMW 320i",
    image: "",
    images: [],
    description: "Dummy listing for 2018 BMW 320i Sport Line. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2017-audi-a3-attraction",
    title: "2017 Audi A3 Attraction",
    price: 21990,
    kms: "119,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Sedan",
    colour: "Grey",
    engine: "1.4L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG018",
    imageLabel: "Audi A3",
    image: "",
    images: [],
    description: "Dummy listing for 2017 Audi A3 Attraction. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Comfort seats", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2020-hyundai-tucson-active",
    title: "2020 Hyundai Tucson Active",
    price: 24990,
    kms: "79,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "White",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG019",
    imageLabel: "Hyundai Tucson",
    image: "",
    images: [],
    description: "Dummy listing for 2020 Hyundai Tucson Active. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2015-toyota-hilux-sr",
    title: "2015 Toyota Hilux SR",
    price: 27990,
    kms: "188,000 km",
    transmission: "Automatic",
    fuel: "Diesel",
    warranty: "Warranty available",
    body: "Ute",
    colour: "Silver",
    engine: "2.8L Turbo Diesel",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG020",
    imageLabel: "Toyota Hilux",
    image: "",
    images: [],
    description: "Dummy listing for 2015 Toyota Hilux SR. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Tow bar option", "Bluetooth", "Cruise control", "Tray/utility body", "Air conditioning", "Service history"]
  },
  {
    id: "2021-haval-h6-premium",
    title: "2021 Haval H6 Premium",
    price: 21990,
    kms: "58,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Blue",
    engine: "2.0L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG021",
    imageLabel: "Haval H6",
    image: "",
    images: [],
    description: "Dummy listing for 2021 Haval H6 Premium. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-mazda-3-neo-sport",
    title: "2018 Mazda 3 Neo Sport",
    price: 15990,
    kms: "124,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Hatchback",
    colour: "Red",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG022",
    imageLabel: "Mazda 3",
    image: "",
    images: [],
    description: "Dummy listing for 2018 Mazda 3 Neo Sport. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2019-nissan-qashqai-st",
    title: "2019 Nissan Qashqai ST",
    price: 20990,
    kms: "95,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Grey",
    engine: "2.0L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG023",
    imageLabel: "Nissan Qashqai",
    image: "",
    images: [],
    description: "Dummy listing for 2019 Nissan Qashqai ST. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2016-suzuki-swift-gl",
    title: "2016 Suzuki Swift GL",
    price: 11990,
    kms: "134,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Hatchback",
    colour: "White",
    engine: "1.4L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG024",
    imageLabel: "Suzuki Swift",
    image: "",
    images: [],
    description: "Dummy listing for 2016 Suzuki Swift GL. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2020-volkswagen-tiguan-110tsi",
    title: "2020 Volkswagen Tiguan 110TSI",
    price: 29990,
    kms: "84,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Black",
    engine: "1.4L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG025",
    imageLabel: "Volkswagen Tiguan",
    image: "",
    images: [],
    description: "Dummy listing for 2020 Volkswagen Tiguan 110TSI. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2018-holden-trax-ls",
    title: "2018 Holden Trax LS",
    price: 14990,
    kms: "106,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "Orange",
    engine: "1.4L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG026",
    imageLabel: "Holden Trax",
    image: "",
    images: [],
    description: "Dummy listing for 2018 Holden Trax LS. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2017-ford-focus-trend",
    title: "2017 Ford Focus Trend",
    price: 13990,
    kms: "118,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "Hatchback",
    colour: "Silver",
    engine: "1.5L Turbo",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG027",
    imageLabel: "Ford Focus",
    image: "",
    images: [],
    description: "Dummy listing for 2017 Ford Focus Trend. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    carsalesUrl: "https://www.carsales.com.au/cars/details/2010-ford-falcon-xr6-fg-auto/OAG-AD-25830603/",
    externalListing: {
      label: "Official Carsales Listing",
      url: "https://www.carsales.com.au/cars/details/2010-ford-falcon-xr6-fg-auto/OAG-AD-25830603/",
      text: "This vehicle is also advertised online. Open the Carsales listing for the live advertisement details."
    },
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2019-toyota-yaris-ascent",
    title: "2019 Toyota Yaris Ascent",
    price: 15990,
    kms: "89,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "Hatchback",
    colour: "White",
    engine: "1.3L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG028",
    imageLabel: "Toyota Yaris",
    image: "",
    images: [],
    description: "Dummy listing for 2019 Toyota Yaris Ascent. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    carsalesUrl: "https://www.carsales.com.au/cars/details/2010-ford-falcon-xr6-fg-auto/OAG-AD-25830603/",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Air conditioning", "Service history", "Alloy wheels"]
  },
  {
    id: "2016-jeep-cherokee-longitude",
    title: "2016 Jeep Cherokee Longitude",
    price: 17990,
    kms: "139,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty option",
    body: "SUV",
    colour: "Black",
    engine: "3.2L V6",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG029",
    imageLabel: "Jeep Cherokee",
    image: "",
    images: [],
    description: "Dummy listing for 2016 Jeep Cherokee Longitude. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  },
  {
    id: "2021-mitsubishi-outlander-es",
    title: "2021 Mitsubishi Outlander ES",
    price: 27990,
    kms: "72,000 km",
    transmission: "Automatic",
    fuel: "Petrol",
    warranty: "Warranty available",
    body: "SUV",
    colour: "Silver",
    engine: "2.4L 4 Cylinder",
    rego: "Available on request",
    vin: "Available on request",
    stockNo: "KHG030",
    imageLabel: "Mitsubishi Outlander",
    image: "",
    images: [],
    description: "Dummy listing for 2021 Mitsubishi Outlander ES. Replace this text, photos, price and specifications with the real vehicle details before publishing.",
    features: ["Reverse camera", "Bluetooth", "Cruise control", "Spacious boot", "Air conditioning", "Alloy wheels"]
  }
];

const services = [
  { title: "Paintless Dent Removal", text: "Remove minor dents while keeping the original paint finish where suitable." },
  { title: "Spray Painting", text: "Quality automotive paint refinishing for repaired panels and cosmetic restoration." },
  { title: "Panel Beating", text: "Dent, accident and body repair support to help your car look right again." },
  { title: "RWC Checks", text: "Roadworthy inspection support before selling, buying or re-registering a vehicle." },
  { title: "Auto Electrical Repairs", text: "Battery, electrical fault and vehicle system checks for modern vehicles." },
  { title: "Air Conditioning", text: "Car air conditioning inspection, repairs and gas refill support where required." },
  { title: "Mechanical Repairs", text: "General mechanical repairs and servicing for many makes and models." },
  { title: "Maintenance Services", text: "Regular maintenance checks to help keep your vehicle reliable and road-ready." },
  { title: "Car Body Repairs", text: "Scratch, dent and car body repair assistance for minor and major body damage." },
  { title: "European Auto Repairs", text: "Workshop support for European vehicles with experienced technicians." }
];

const reviews = [
  { name: "Hemant Khande", title: "Super quick service", text: "Got my car tyre puncture fixed. Super quick and reasonable price. I would recommend this shop." },
  { name: "Barbershop Convo", title: "Best in business", text: "Best in business, always supporting, and truthfully advising. Please go and visit the workshop!" },
  { name: "Lee Benson", title: "Good quality and prices", text: "I had my car body repair at KHG and I am so happy with the service, good quality and good prices." },
  { name: "Kanak Jagarlamudi", title: "Nice service and assistance", text: "Bought a car here, very nice service and assistance. Must check out if you want to buy a used car or car services." },
  { name: "Zale Ath", title: "Great value", text: "Great value and efficient service. Had brake pads front and rear replaced within 3 hours for a very reasonable price. Highly recommended!" },
  { name: "Sam", title: "Exceptional service", text: "Exceptional service, professional, efficient and super friendly. Very competitive with price and the workmanship is second to none." }
];
